### ISSUE TITLE
Update the documentation with the new `preset` configuration option

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#37]
The newly added `preset` property can now be used to merge multiple configuration, we can now ditch the use of the `merge` function from lodash.

- [x] Update the documentation to use the `preset` property
- [ ] Add a preset property to this config to inherit from the default Tailwind config

```js
module.exports = {
  presets: [require('tailwindcss/defaultConfig')],
};
```

**Comment by notjb** [comment]
@titouanmathis based on https://tailwindcss.com/docs/presets adding a `presets: [require('tailwindcss/defaultConfig')]` is not mandatory : when not preset object is given, it will extend the default config.

Fun fact, giving an empty `preset: []` will remove the default config.
