### ISSUE TITLE
Add experimental and future configuration

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#38]
We always add the following configuration, we should add it to this package instead.

```js
module.exports = {
  experimental: {
    applyComplexClasses: true,
  },
  future: {
    purgeLayersByDefault: true,
  },
};
```

**Comment by notjb** [comment]
As of 2.0, tailwind doesn't use the `future` and `experimental` configuration options cf. https://tailwindcss.com/docs/upgrading-to-v2#remove-future-and-experimental-configuration-options

I think we can close this.

**Comment by titouanmathis** [comment]
👍
