### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#5]
How should we structure the project's documentation?

I have the following structure in mind:

- Configuration → describe the configuration 
- Plugins → describe each plugin
  - Debug
  - Grid
- Migration guide → how to migrate
  - From @studiometa/scss-toolkit to @studiometa/tailwind-config
  - ...

@studiometa/css what should/could we add? remove?

**Comment by perruche** [comment]
We could add :
- How to extend the configuration
- Best practices
- Use case / exemple of code

I'm not sure about the need to write a migration guide. Didn't we say we would not change existing projects ?

**Comment by titouanmathis** [comment]
>  I'm not sure about the need to write a migration guide. Didn't we say we would not change existing projects ?

The migration guide would be more to explain the small differences between the SCSS Toolkit and this configuration: the naming of the grid's classes, a mapping of the old utility classes to the new ones, etc.

**Comment by titouanmathis** [comment]
Proposal for the documentation:

1. Installation → how to install the configuration
2. Usage → how to use it basic and advanced
3. Configuration → what is specific about this configuration: rules disabled, plugins, etc.
4. Custom plugins → the custom plugins used
5. Best practices → @perruche what was your idea for this section? Isn't the official documentation enough?
6. Demo + examples
7. Ressources → external doc, articles and more

**Comment by perruche** [comment]
Something like the do's and don'ts. 
Like for exemple enforce the use of `@apply` to keep html easily readable.
