### ISSUE TITLE
Extend breakpoint configuration

### ISSUE THREAD

**Issue by perruche** [studiometa/tailwind-config#63]
- Extend breakpoint configuration to have more breakpoints for larger screens
- Rename `xxl` to `2xl` prefix to follow tailwind naming (This could break some rules in old project)

**Comment by antoine4livre** [comment]
@perruche @titouanmathis What are the needed new breakpoints ?

**Comment by perruche** [comment]
I would say breakpoints for large screens, maybe more granularity between `l` and `2xl` and maybe add one `3xl` for big big screens ?

**Comment by antoine4livre** [comment]
@titouanmathis Have you some values in mind ? I have found this tool that can help us to choose : https://screensiz.es/

**Comment by titouanmathis** [comment]
I think the following might be nice: 

```
    screens: {
      2xs: '0px',
      xs: '480px',
      s: '768px',
      m: '1024px',
      l: '1280px',
      xl: '1440px',
      2xl: '1920px',
      3xl: '2560px',
    },
```

And we could remove the configuration `smallestBreakpointName` in the breakpoint plugin, as it would be inferred by the `2xs` key. 

What do you think about renaming the keys to match Tailwind naming convention?

```
s → sm
m → md
l → xl
```

cc @studiometa/core

**Comment by perruche** [comment]
> I think the following might be nice:
> 
> ```
>     screens: {
>       2xs: '0px',
>       xs: '480px',
>       s: '768px',
>       m: '1024px',
>       l: '1280px',
>       xl: '1440px',
>       2xl: '1920px',
>       3xl: '2560px',
>     },
> ```
> 
> And we could remove the configuration `smallestBreakpointName` in the breakpoint plugin, as it would be inferred by the `2xs` key.
> 
> What do you think about renaming the keys to match Tailwind naming convention?
> 
> ```
> s → sm
> m → md
> l → xl
> ```
> 
> cc @studiometa/core

I do not see advantages to switch (to longer) names. This seems inherited from bootstrap breakpoint names.
Always think that this naming is base on t-shirt sizes, so `sm`, `md`, `lg` does not make sense to me 😸

**Comment by antoine4livre** [comment]
How about this?

```
    screens: {
      xxs: '0px',
      xs: '480px',
      s: '768px',
      m: '1024px',
      l: '1280px',
      xl: '1440px',
      xxl: '1920px',
      xxxl: '2560px',
    },
```

**Comment by antoine4livre** [comment]
I'm waiting for your confirmation. I will add the new breakpoints in #71

**Comment by titouanmathis** [comment]
> How about this?
> 
> ```
>     screens: {
>       xxs: '0px',
>       xs: '480px',
>       s: '768px',
>       m: '1024px',
>       l: '1280px',
>       xl: '1440px',
>       xxl: '1920px',
>       xxxl: '2560px',
>     },
> ```

I am ok with this 👍

**Comment by antoine4livre** [comment]
Updated in #72 🙂 @titouanmathis @perruche
