### ISSUE TITLE
Update configuration to follow more closely the defaults

### ISSUE THREAD

**Issue by titouanmathis** [studiometa/tailwind-config#71]
- [x] Prefix the grid plugin classes with `meta-` or `legacy-` 
- [x] Re-enable the `display` core plugin 
- [x] Remove colors from the config (everything is defined in the default config)
- [x] Move `zIndex` configuration to `extend` 
- [x] Delete the debug-outline plugin
- [x] Delete the obsolete `variants` property
- [x] Add a `generateZIndexes({ name: value })` utility function to generate `name-under: value - 1` and `name-above: value + 1` classes

**Comment by antoine4livre** [comment]
- [ ] Add a `display: grid;` grid demo in the documentation
